configfile: 'config.yaml'

include: 'rules/coverage-analysis.smk'

# bin samples based on coverage and compare
rule coverage_experiments:
    input:
        'results/coverage-experiments/plots/all.pdf',
        'results/sv_count_per_sample/plot.pdf'

# downsampling a high coverage sample and genotyping it
# samples with coverage > 100 is HG02013 and HG00377.
#rule downsampling_experiments:
#    input:
#        'results/downsampling-experiments/'
        