# samples in common between Miller set, Vienna set and the 1000GP unrelated set
# HG03499
# HG03548

# path of the CHM13-T2T CRAMs
# Files are available here https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1KG_ONT_VIENNA/t2t/
path_to_t2t_cram: '/gpfs/project/projects/medbioinf/data/share/globus/hhu-1000g-ont/t2t/'

# path to the reference fasta used to create the CRAMS
# reference is available here https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1KG_ONT_VIENNA/reference/
# this directory should contain the files 1KG_ONT_VIENNA_t2t.fa and 1KG_ONT_VIENNA_hg38.fa along with their .fai index
# the directory of the reference
reference_directory: "/gpfs/project/projects/medbioinf/users/spani/files/ref/"

# path to HGSVC3 assembly alignments
path_to_hgsvc_alignments: '/gpfs/project/projects/medbioinf/projects/assemblies/hybrids/eval/wd/results/alignments/contig_to_ref/t2tv2/bam/'

# Not used by the pipeline currently

# The VAMOS vcf made from the NAPU assemblies of Gustafson et al can be downloaded at https://drive.google.com/file/d/1nykyQtunVptujJc_lkEUZUYZczASL0mb/view?usp=drive_link
path_to_miller_vcf: '/gpfs/project/projects/medbioinf/users/spani/files/vcf/1000GP/MillerLab-Vamos/S3_1kgp_updated_combined.vcf.gz'

