configfile: 'config.yaml'

include: 'rules/get-sample-list.smk'
include: 'rules/hgsvc-qc.smk'
include: 'rules/vamos.smk'
include: 'rules/analysis.smk'
include: 'rules/rare-disease-analysis.smk'

comaprison_samples = ['HG03499','HG03548']
haplotypes = ['hap1', 'hap2']

wildcard_constraints:
    sample='|'.join(cram_sample_list+hgsvc_sample_list_all),
    haplotype='|'.join(haplotypes)

rule all:
    input:
        'results/vamos-t2t-summary.bed',
        'results/vamos-multisample.vcf',
        'results/hgsvc3-comparison/qc/ru-boxplot-pcc.svg',
        'results/hgsvc3-comparison/hgsvc-vntr-summary.bed',
        'results/hgsvc3-comparison/vntr-spread/max-full.svg',
        'results/rare-disease-vntr-analysis/abca7-histogram.svg',
        'results/rare-disease-vntr-analysis/plin4-histogram.svg',
        'results/per-sample-bed/reference-vntrs-t2t-seq.bed',
        'results/per-sample-bed/chm13-prep/chm13-vntr.vcf',
        'results/per-sample-bed/chm13-prep/chm13-vntr.stats',
        expand('results/per-sample-bed/bed/{sample}.bed', sample=cram_sample_list),
        expand('results/per-sample-bed/vcf/{sample}.vcf.gz', sample=cram_sample_list),
        'results/per-sample-bed/bed-stats.tsv'
        