configfile: 'config.yaml'

include: 'rules/vamos.smk'
include: 'rules/analysis.smk'

samples = ['HG03499','HG03548']
afs = ['0.1', '0.5', '1']

wildcard_constraints:
    sample='|'.join(samples),
    af='|'.join(afs)

rule all:
    input:
        expand('results/vamos-results-vienna/{sample}.vcf', sample=samples),
        expand('results/plots/distance-histogram/{sample}-{af}-subset1000.png', sample=samples, af=afs),
        expand('results/plots/distance-histogram/{sample}-{af}-full.png', sample=samples, af=afs),
        expand('results/plots/distance-histogram/HG03499_HG03548-{af}-subset1000.png', af=afs),
        expand('results/plots/distance-histogram/HG03548_HG03499-{af}-subset1000.png', af=afs),
        expand('results/plots/distance-histogram/HG03499_HG03548-{af}-full.png', af=afs),
        expand('results/plots/distance-histogram/HG03548_HG03499-{af}-full.png', af=afs)
