configfile: 'config.yaml'

include: 'rules/prepare-vcf.smk'
include: 'alignment-experiment.smk'

rule run_alignment_experiments:
    input:
        'results/assembly-to-graph-alignment-experiments/collated-statistics.tsv'

rule all:
    input:
        'results/assembly-vcf/chimp.vcf'
        