configfile: 'config.yaml'

include: 'rules/extract-sample-list.smk'
include: 'rules/coverage-analysis.smk'
include: 'rules/n50-analysis.smk'

# bin samples based on coverage and compare
rule coverage_experiments:
    input:
        'results/coverage-experiments/qc-plots/all.pdf',
        'results/coverage-experiments/sv_count_per_sample/plot.svg'

# bin samples based on n50 and compare
rule n50_experiments:
    input:
        'results/n50-experiments/qc-plots/all.pdf',
        'results/n50-experiments/sv_count_per_sample/plot.svg'

rule all:
    input:
        rules.coverage_experiments.input,
        rules.n50_experiments.input