configfile: 'config.yaml'

include: 'rules/genotyping.smk'
include: 'rules/ont-alignment.smk'
include: 'rules/prepare-vcf.smk'
include: 'rules/bubble-tagging.smk'
include: 'rules/common-rules.smk'
include: 'rules/get-sample-list.smk'
include: 'rules/self-genotyping.smk'
include: 'rules/callset-comparisons.smk'

wildcard_constraints:
    sample='|'.join(samples)

rule all:
    input:
        expand('results/{callset}/genotypes/multisample-multiallelic.vcf.gz', callset = [c for c in config['callsets'].keys()]),
        expand('results/{callset}/genotypes/multisample-biallelic.vcf.gz', callset = [c for c in config['callsets'].keys()]),
        expand('results/{callset}/self-genotyping/concordance-{representation}/summary_{min_af}-{max_af}.tsv', 
                    callset = [c for c in config['callsets'].keys()], 
                    representation=['biallelic', 'multiallelic'], 
                    min_af=['0', '0.05', '0.1', '0.2'], 
                    max_af=['1'])